2024-10-09 20:54:30,309, WARNING, Неверный тип данных для объекта Runner, test_run, 38
Traceback (most recent call last):
  File "C:\Users\SHLIC\UrbanProjects\pythonProject\test_12_4.py", line 32, in test_run
    runner = Runner(5, 5)
  File "C:\Users\SHLIC\UrbanProjects\pythonProject\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-09 20:54:30,309, WARNING, Неверная скорость для Runner, test_walk, 27
Traceback (most recent call last):
  File "C:\Users\SHLIC\UrbanProjects\pythonProject\test_12_4.py", line 21, in test_walk
    walker = Runner('Павел', -1)
  File "C:\Users\SHLIC\UrbanProjects\pythonProject\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -1
